// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ConnectAccount(arg1:string):Promise<void>;

export function CreatePost(arg1:models.Post):Promise<models.Post>;

export function CreateTask(arg1:models.Task):Promise<models.Task>;

export function DeletePost(arg1:number):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function DisconnectAccount():Promise<void>;

export function GetDashboardStats():Promise<models.DashboardStats>;

export function GetLogs():Promise<Array<models.Log>>;

export function GetPosts():Promise<Array<models.Post>>;

export function GetSettings():Promise<models.Settings>;

export function GetTasks():Promise<Array<models.Task>>;

export function RunTaskOnce(arg1:number):Promise<void>;

export function UpdatePost(arg1:models.Post):Promise<models.Post>;

export function UpdateSettings(arg1:models.Settings):Promise<void>;

export function UpdateTask(arg1:models.Task):Promise<models.Task>;
