// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectAccount(arg1) {
  return window['go']['app']['App']['ConnectAccount'](arg1);
}

export function CreatePost(arg1) {
  return window['go']['app']['App']['CreatePost'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['app']['App']['CreateTask'](arg1);
}

export function DeletePost(arg1) {
  return window['go']['app']['App']['DeletePost'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['app']['App']['DeleteTask'](arg1);
}

export function DisconnectAccount() {
  return window['go']['app']['App']['DisconnectAccount']();
}

export function GetDashboardStats() {
  return window['go']['app']['App']['GetDashboardStats']();
}

export function GetLogs() {
  return window['go']['app']['App']['GetLogs']();
}

export function GetPosts() {
  return window['go']['app']['App']['GetPosts']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetTasks() {
  return window['go']['app']['App']['GetTasks']();
}

export function RunTaskOnce(arg1) {
  return window['go']['app']['App']['RunTaskOnce'](arg1);
}

export function UpdatePost(arg1) {
  return window['go']['app']['App']['UpdatePost'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['app']['App']['UpdateSettings'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['app']['App']['UpdateTask'](arg1);
}
