// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddAccount(arg1:string,arg2:string):Promise<models.FacebookAccount>;

export function CreateReactionTask(arg1:models.ReactionTask):Promise<models.ReactionTask>;

export function DeleteAccount(arg1:string):Promise<void>;

export function GetAccountFriendsList(arg1:string):Promise<Array<string>>;

export function GetAllAccounts():Promise<Array<models.FacebookAccount>>;

export function GetExecutions():Promise<Array<models.TaskExecution>>;

export function GetLogs():Promise<Array<models.ActivityLog>>;

export function GetOverview():Promise<models.DashboardStats>;

export function GetReactionTasks():Promise<Array<models.ReactionTask>>;

export function GetSettings():Promise<models.AppSettings>;

export function LoginAccount(arg1:string,arg2:string,arg3:string):Promise<models.FacebookAccount>;

export function MarkManualCompleted(arg1:number):Promise<void>;

export function PauseReactionTask(arg1:number):Promise<void>;

export function RemoveReactionTask(arg1:number):Promise<void>;

export function RetryReactionTask(arg1:number):Promise<void>;

export function RunReactionTaskNow(arg1:number,arg2:string):Promise<void>;

export function ScanAccountData(arg1:string,arg2:string):Promise<models.FacebookAccount>;

export function ScanAccountFriendsAPI(arg1:string,arg2:string):Promise<number>;

export function SelectPhotoDialog():Promise<string>;

export function UpdateSettings(arg1:models.AppSettings):Promise<void>;

export function ValidateReactionTask(arg1:models.ReactionTask):Promise<string>;
