// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1, arg2) {
  return window['go']['app']['App']['AddAccount'](arg1, arg2);
}

export function CreateReactionTask(arg1) {
  return window['go']['app']['App']['CreateReactionTask'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['app']['App']['DeleteAccount'](arg1);
}

export function GetAccountFriendsList(arg1) {
  return window['go']['app']['App']['GetAccountFriendsList'](arg1);
}

export function GetAllAccounts() {
  return window['go']['app']['App']['GetAllAccounts']();
}

export function GetExecutions() {
  return window['go']['app']['App']['GetExecutions']();
}

export function GetLogs() {
  return window['go']['app']['App']['GetLogs']();
}

export function GetOverview() {
  return window['go']['app']['App']['GetOverview']();
}

export function GetReactionTasks() {
  return window['go']['app']['App']['GetReactionTasks']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function LoginAccount(arg1, arg2, arg3) {
  return window['go']['app']['App']['LoginAccount'](arg1, arg2, arg3);
}

export function MarkManualCompleted(arg1) {
  return window['go']['app']['App']['MarkManualCompleted'](arg1);
}

export function PauseReactionTask(arg1) {
  return window['go']['app']['App']['PauseReactionTask'](arg1);
}

export function RemoveReactionTask(arg1) {
  return window['go']['app']['App']['RemoveReactionTask'](arg1);
}

export function RetryReactionTask(arg1) {
  return window['go']['app']['App']['RetryReactionTask'](arg1);
}

export function RunReactionTaskNow(arg1, arg2) {
  return window['go']['app']['App']['RunReactionTaskNow'](arg1, arg2);
}

export function ScanAccountData(arg1, arg2) {
  return window['go']['app']['App']['ScanAccountData'](arg1, arg2);
}

export function ScanAccountFriendsAPI(arg1, arg2) {
  return window['go']['app']['App']['ScanAccountFriendsAPI'](arg1, arg2);
}

export function SelectPhotoDialog() {
  return window['go']['app']['App']['SelectPhotoDialog']();
}

export function UpdateSettings(arg1) {
  return window['go']['app']['App']['UpdateSettings'](arg1);
}

export function ValidateReactionTask(arg1) {
  return window['go']['app']['App']['ValidateReactionTask'](arg1);
}
